const auth = {
  REGISTER_APPLICANT_REQUEST: "REGISTER_APPLICANT_REQUEST",
  REGISTER_APPLICANT_SUCCESS: "REGISTER_APPLICANT_SUCCESS",
  REGISTER_APPLICANT_ERROR: "REGISTER_APPLICANT_ERROR",

  LOGIN_APPLICANT_REQUEST: "LOGIN_APPLICANT_REQUEST",
  LOGIN_APPLICANT_SUCCESS: "LOGIN_APPLICANT_SUCCESS",
  LOGIN_APPLICANT_ERROR: "LOGIN_APPLICANT_ERROR",

  registerApplicant: (data) => {
    console("REGISTER_APPLICANT_REQUEST", data);
    return {
      type: auth.REGISTER_APPLICANT_REQUEST,
      data,
    };
  },

  loginApplicant: (data) => ({
    type: auth.LOGIN_APPLICANT_REQUEST,
    data,
  }),
};

export default auth;
